const path=require('path')
console.log(path.dirname('D:/BackEnd/PathModule/index.js'))
console.log(path.extname('D:/BackEnd/PathModule/index.js'))
console.log(path.basename('D:/BackEnd/PathModule/index.js'))
console.log(path.parse('D:/BackEnd/PathModule/index.js'))